# Generated by Django 2.0.1 on 2018-02-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20180130_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
